version: '2'

services:
  isb-backend-landindpage:
    container_name: isb-backend-landindpage
    image: isb-backend-landindpage:0.0.1
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 2201:2201
    restart: always